# Generated by Django 4.1.3 on 2022-11-15 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supers', '0002_super_alter_ego_super_catchprase_super_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='super',
            old_name='catchprase',
            new_name='catchphrase',
        ),
    ]
